name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: sample-app
  IMAGE_TAG: ${{ github.sha }}
  # Artifact Registry URI
  IMAGE_URI: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sample-repo/sample-app:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run tests (if any)
        run: |
          echo "No tests defined. Add your tests here."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Create Artifact Registry repository
        run: |
          # Check if repository exists
          if gcloud artifacts repositories describe sample-repo --location=us-central1 --project=${{ secrets.GCP_PROJECT_ID }} --quiet 2>/dev/null; then
            echo "Repository 'sample-repo' already exists"
          else
            echo "Creating repository 'sample-repo'..."
            gcloud artifacts repositories create sample-repo \
              --repository-format=docker \
              --location=us-central1 \
              --project=${{ secrets.GCP_PROJECT_ID }} \
              --description="Sample Docker repository for CI/CD pipeline"
          fi

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_URI -f docker/Dockerfile .
          docker push $IMAGE_URI

  terraform-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
